(function(g){var window=this;'use strict';var ffb=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.USa)("0",Math.max(0,b-c))+a},gfb=function(){return{G:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},W:[{G:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},hfb=function(){return{G:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},W:[{G:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},jfb=function(a){"number"===typeof a?(this.date=ifb(a,0,1),R5(this,1)):g.Ha(a)?(this.date=ifb(a.getFullYear(),a.getMonth(),a.getDate()),R5(this,a.getDate())):(this.date=new Date(g.Qa()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),R5(this,a))},ifb=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},R5=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},S5=function(a,b){g.hR.call(this,a,{G:"div",
N:"ytp-reminder-menu",X:{role:"menu",tabindex:"-1"},W:[{G:"div",N:"ytp-reminder-menu-contents",W:[{G:"div",N:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Ca("ytp-reminder-menu-items");this.hide()},lfb=function(a){var b=kfb(a),c=0,d={};
for(c=0;c<b.length;d={SH:d.SH},c++){var e=a.j[c];e||(e=new g.S({G:"div",N:"ytp-reminder-menu-item",X:{role:"menuitem",tabindex:"0"},W:[{G:"div",N:"ytp-reminder-menu-item-icon",qa:"{{icon}}"},{G:"div",N:"ytp-reminder-menu-item-label",qa:"{{text}}"}]}),d.SH=c,e.Pa("click",function(l){return function(){var m=l.SH;a.Bb();m=kfb(a)[m];a.ea("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Da(a.items),a.j[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=gfb();break;case "NOTIFICATIONS_NONE":h=hfb();break;case "NOTIFICATIONS_ACTIVE":h=g.UN()}f=f.text?g.hC(f.text):"";e.update({icon:h,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.Bb():a.Pc(a.buttonElement)},kfb=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},T5=function(a){g.S.call(this,{G:"div",
W:[{G:"button",Ia:["ytp-offline-slate-button","ytp-button"],W:[{G:"div",N:"ytp-offline-slate-button-icon",qa:"{{icon}}"},{G:"div",N:"ytp-offline-slate-button-text",qa:"{{text}}"}]}]});this.F=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.C=this.j=null;(this.buttonElement=this.Ca("ytp-offline-slate-button"))&&this.S(this.buttonElement,"click",this.D);this.hide()},nfb=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.L(c,mfb)?a.upcomingEventReminderButtonRenderer=g.L(c,mfb):c&&g.L(c,mfb)||(a.upcomingEventReminderButtonRenderer=null);U5(a)},U5=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.hC(b.toggledText):"";a.update({text:c,icon:ofb(b.toggledIcon)})}else c=b.defaultText?g.hC(b.defaultText):"",a.update({text:c,icon:ofb(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=pfb(a))?(c=b.text?g.hC(b.text):"",a.update({text:c,icon:ofb(b.icon)}),a.show()):a.hide():a.hide()},rfb=function(a,b,c){a.C||(a.C=new g.Hz(a.F.T().Hk));
var d={context:g.ez(a.C.config_||g.Ty())};g.GC()&&(d.context.clientScreenNonce=g.GC());d.params=c;g.Iz(a.C,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){qfb(a)},
onTimeout:function(){qfb(a)}})},qfb=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,U5(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,U5(a))},ofb=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return gfb();case "NOTIFICATIONS_NONE":return hfb();case "NOTIFICATIONS_ACTIVE":return g.UN();default:return null}},pfb=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.t(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.L(c.value,sfb))&&c.state===b&&c.button&&g.L(c.button,g.eK))return g.L(c.button,g.eK);return null},tfb=function(a){g.S.call(this,{G:"div",
N:"ytp-offline-slate",W:[{G:"div",N:"ytp-offline-slate-background"},{G:"div",N:"ytp-offline-slate-bar",W:[{G:"span",N:"ytp-offline-slate-icon",W:[{G:"svg",X:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},W:[{G:"path",X:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",X:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",N:"ytp-offline-slate-messages",W:[{G:"div",N:"ytp-offline-slate-main-text",X:{"aria-label":"{{label}}"},qa:"{{mainText}}"},{G:"div",N:"ytp-offline-slate-subtitle-text",qa:"{{subtitleText}}"}]},{G:"span",N:"ytp-offline-slate-buttons"}]},{G:"button",Ia:["ytp-offline-slate-close-button","ytp-button"],W:[g.PN()]},{G:"button",Ia:["ytp-offline-slate-open-button","ytp-button"],W:[g.ON()]}]});var b=this;this.api=a;this.j=this.u=null;this.background=this.Ca("ytp-offline-slate-background");
this.B=this.Ca("ytp-offline-slate-bar");this.D=new g.Yn(function(){g.go(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.I=!1;this.C=new g.Yn(function(){g.go(b.element,"ytp-offline-slate-collapsed")},15E3);
g.D(this,this.C);g.D(this,this.D);this.countdownTimer=new g.Yn(this.MX,1E3,this);this.S(a,"presentingplayerstatechange",this.RX);this.S(a,"livestatedata",this.La);var c=this.Ca("ytp-offline-slate-close-button");this.S(c,"click",function(){g.go(b.element,"ytp-offline-slate-collapsed")});
c=this.Ca("ytp-offline-slate-open-button");this.S(c,"click",function(){g.io(b.element,"ytp-offline-slate-collapsed")});
this.hide();c=this.getVideoData();c.getPlayerResponse()&&(c=c.getPlayerResponse().playabilityStatus)&&this.La(c);c=8===this.api.getPresentingPlayerType()&&!this.getVideoData().dl;var d=8===this.api.getPresentingPlayerType();g.ko(this.element,"ytp-offline-slate-premiere-trailer",c);g.ko(this.element,"ytp-offline-slate-hide-background",d);a.K("web_rounded_containers")&&g.go(this.B,"ytp-rounded-offline-slate")},ufb=function(a,b,c){if(b){var d=null!=b.subtitleText?g.hC(b.subtitleText):"";
c=c?c:null!=b.mainText?g.hC(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.ko(a.element,"ytp-offline-slate-single-text-line",!d);g.ko(a.B,"ytp-offline-slate-bar-hidden",!c&&!d)}},V5=function(a,b){var c=(0,g.M)();
this.module="heartbeat";this.trigger=a;this.j=b;this.B=c},Cfb=function(a){g.RR.call(this,a);
var b=this;this.J=!1;this.V=0;this.D=!1;this.u=new g.Yn(function(){var e=b.player.T(),f=b.getVideoData();W5(b)&&(vfb(b)?wfb(b,e,f):(xfb(b),yfb(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.C=!1;this.I=new g.Kh(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.ma=new g.Hz(void 0);this.Y=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new jfb).getTimezoneOffset();this.B=new g.ZF(this);g.D(this,this.u);g.D(this,this.B);xfb(this);zfb(this);this.B.S(a,"heartbeatparams",this.AC);this.B.S(a,"presentingplayerstatechange",this.nZ);this.B.S(a,"videoplayerreset",this.oZ);this.B.S(a,g.$B("heartbeat"),this.onCueRangeEnter);this.C&&this.j&&
Afb(this,this.j);var c=new g.YB(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.YB(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.Me([c,d]);Bfb(this)},Bfb=function(a){var b=a.getVideoData();
b.Yl&&(b=b.botguardData)&&g.aQ(b,a.player.T())},xfb=function(a){var b=a.getVideoData();
if(b.Yl&&(b=new g.fKa(b),g.SP.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.gk){var d=g.gKa(b);if(d){c={};var e={};d=d.split("&");d=g.t(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=Dfb[Number(e.r1c)]);c.challenge=b.videoData.gk}}a.attestationResponse=c||void 0}},vfb=function(a){var b=a.getVideoData();
if(!g.qK(a.getVideoData())||b.bS)return!1;if(b.useInnertubeDrmService()&&b.J){a="playready"===b.J.flavor&&b.K("html5_innertube_heartbeats_for_playready");var c="widevine"===b.J.flavor&&b.K("html5_innertube_heartbeats_for_widevine");b=g.YG(b.J)&&b.K("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},Efb=function(a){if(vfb(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.qK(a.getVideoData())&&b.useInnertubeDrmService()&&!b.Vl&&!b.qI?!1:!!b.heartbeatToken},X5=function(a,b){if(!a.u.isActive()&&a.J){var c=a.getVideoData();
if(Efb(a)||c.isLivePlayback){if(void 0===b)if(a.D)if(a.C)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().wR||6E4}else b=1E3;a.u.start(b)}}},Ifb=function(a,b,c){b.mm&&(c=g.$h(c,{internalipoverride:b.mm}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.ac&&(d.kpt=b.ac);c=g.$h(c,d);g.Gw(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&W5(a)){a.I.reset();a.sequenceNumber++;e=e.responseText;var f=Ffb(e);if(f){a.player.Na("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(Gfb))?"0"===h[1]?0:1:-1;Hfb(a,f,e,h)}},
onError:function(e){W5(a)&&Y5(a,!0,"net-"+e.status)},
onTimeout:function(){W5(a)&&Y5(a,!0,"timeout")},
withCredentials:!0})},wfb=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.$h(a.heartbeatParams.url,{request_id:g.usa()});c.Aa&&(e=g.$h(e,{vvt:c.Aa}),c.mdxEnvironment&&(e=g.$h(e,{mdx_environment:c.mdxEnvironment})));g.EI(b,c.oauthToken).then(function(f){f&&(e=g.$h(e,{access_token:f}));Ifb(a,c,e)})}},W5=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.R(a.player.Fb(a.getPlayerType()),4)?!1:Efb(a)||b.isLivePlayback?!0:(Z5(a),!1)},yfb=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.oa)?d:c.heartbeatServerData};a.Y=a.attestationResponse;c.Yl&&(e.attestationResponse=a.Y);var f=g.sQ(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.wI(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=Jfb(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.vb())?void 0:g.hS(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;c.isLivePlayback&&(l=Jfb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l}));a.player.ea("heartbeatRequest",e);var n={timeout:3E4,onSuccess:function(p){if(!a.u.isActive()&&W5(a)){var q=a.getVideoData(),r=q.Yl&&null==a.Y,w;q.Yl=!(null==(w=p.heartbeatAttestationConfig)||!w.requiresAttestation)||r;r=p.playabilityStatus;w=JSON.stringify(r)||"{}";p.authenticationMismatch&&a.player.xa("authshear",{});var x=-1;var z=p.playabilityStatus;z&&(a.player.Na("onHeartbeat",
z),"OK"===z.status?x=p.stopHeartbeat?2:0:"UNPLAYABLE"===z.status?x=1:"LIVE_STREAM_OFFLINE"===z.status&&(x=0));a.sequenceNumber&&-1===x||a.I.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.oa=p.heartbeatServerData);q.bJ=p;p.playerCueRanges&&0<p.playerCueRanges.length&&(q.cueRanges=p.playerCueRanges,q.ea("dataupdated"));Hfb(a,r,w,x)}},
onError:function(p){W5(a)&&Y5(a,!0,"net-"+p.status)},
onTimeout:function(){W5(a)&&Y5(a,!0,"timeout")}};
g.EI(b,g.KK(c)).then(function(p){p&&(n.IR="Bearer "+p);g.Iz(a.ma,"player/heartbeat",e,n)})},Hfb=function(a,b,c,d){-1===d?(b="decode "+g.rf(c,3),Y5(a,!1,b)):2===d?(Z5(a),a.D=!0):(a.V=0,a.u.stop(),1===d?(a.D=!1,a.player.Jg("heartbeat.stop",2,a.zf(c)),g.Tx("heartbeatActionPlayerHalted",Kfb(b))):(a.D=!0,c=0,a.C&&b&&(c=Afb(a,b),a.player.ea("livestatedata",b)),c?X5(a,c):X5(a)))},Afb=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!(c.switchStreamsImmediately||
c.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===c.transitionTiming)),e=Lfb(c),f=a.getVideoData(),h=a.player.Fb(a.getPlayerType()),l=h.bd()&&!g.wK(f)&&!a.player.isAtLiveHead(a.getPlayerType());
if(f.T().Rd()){var m,n=(null==(m=a.player.xe())?void 0:m.lc())||{};n.status=b.status||"";n.dvr=""+ +l;n["switch"]=""+ +d;n.ended=""+ +!(!c||!c.displayEndscreen);a.player.xa("heartbeat",n)}if(l&&!d)return e;d=c&&c.streamTransitionEndpoint&&g.L(c.streamTransitionEndpoint,g.wJ);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(c&&c.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=d;else{if(l=d)(l=d&&d.videoId)?(a.player.Fn(l,{autonav:"1"},void 0,!0,!0,d,g.KK(a.getVideoData())),a.XF("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE",
"HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",b),l=!0):l=!1;if(l)return e}if("OK"===b.status.toUpperCase()){d=c&&c.broadcastId;l=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;m=d!==l&&null!=d;if(!f.hlsvp&&!f.zb||m){var p={video_id:f.videoId};f.iJ&&(p.is_live_destination="1");a.player.K("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.kd);
p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;p.force_gvi=f.lm;p.Il=f.Il;f.V&&(p.vss_credentials_token=f.V,p.vss_credentials_token_type=f.Zj);f.Aa&&(p.vvt=f.Aa);c=void 0;f.hlsvp||f.zb?m&&(c=new V5("broadcastIdChanged",l+","+d),a.XF("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(d&&(c=new V5("formatsReceived",""+d)),a.XF("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b));a.player.loadVideoByPlayerVars(p,
void 0,void 0,void 0,c);return e}a.player.Zf("heartbeat",a.getPlayerType())}c&&c.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.I=!0,a.tb&&a.api.vz()):g.AM(h)&&(f=(null==(p=a.player.xe())?void 0:p.lc())||{},a.player.xa("hbse",f,!0),a.player.vz(),a.player.Na("onLiveMediaEnded",b)));return e},Lfb=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},Y5=function(a,b,c){var d=a.player.T();
if(!a.u.isActive()){a.u.stop();a.V++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.yR||b&&!g.qK(a.getVideoData())&&!Efb(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.mz)?h=a.heartbeatParams.mz:h=f.xR||5;f=a.V>=h}f?(g.Tx("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:Kfb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.Jg(e,1,"\u89c6\u9891\u64ad\u653e\u5df2\u4e2d\u65ad\uff0c\u8bf7\u91cd\u8bd5\u3002",c):a.player.Jg(e,
1,"\u5f88\u62b1\u6b49\uff0c\u4e3a\u6b64\u89c6\u9891\u6388\u4e88\u8bb8\u53ef\u65f6\u51fa\u9519\u3002",c)):(d.K("html5_report_non_fatal_heartbeat_error")&&a.player.Mq(e,{msg:c}),X5(a,a.I.getValue()),g.Lh(a.I))}},Kfb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},Z5=function(a){a.V=0;
a.u.stop();a.D=!1;a.sequenceNumber=0},zfb=function(a){var b=a.getVideoData(),c=a.player.T();
if(b.isLivePlayback)if(g.iH(c.D)){a.C=!0;a.J=!0;if(!g.kI(c)||g.wI(c))a.offlineSlate=new tfb(a.player),g.D(a,a.offlineSlate),g.UQ(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;"UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)&&(a.j?(d=Lfb(a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?X5(a,d):X5(a,7500):X5(a,1E3))}else a.player.Jg("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else g.ib(b.Ka,
"heartbeat")&&a.player.Zf("heartbeat",a.getPlayerType())},Jfb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},Ffb=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},Dfb=["ATTESTATION_ERROR_UNKNOWN",
"ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];var Mfb={KY:["BC","AD"],JY:["Before Christ","Anno Domini"],h0:"JFMAMJJASOND".split(""),B0:"JFMAMJJASOND".split(""),e0:"January February March April May June July August September October November December".split(" "),A0:"January February March April May June July August September October November December".split(" "),v0:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),D0:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),T0:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
F0:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),x0:"Sun Mon Tue Wed Thu Fri Sat".split(" "),E0:"Sun Mon Tue Wed Thu Fri Sat".split(" "),j0:"SMTWTFS".split(""),C0:"SMTWTFS".split(""),w0:["Q1","Q2","Q3","Q4"],r0:["1st quarter","2nd quarter","3rd quarter","4th quarter"],nY:["AM","PM"],BY:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],J0:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],CY:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],HP:6,
U0:[5,6],IP:5};
Mfb={KY:["\u516c\u5143\u524d","\u516c\u5143"],JY:["\u516c\u5143\u524d","\u516c\u5143"],h0:"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),B0:"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),e0:"\u4e00\u6708 \u4e8c\u6708 \u4e09\u6708 \u56db\u6708 \u4e94\u6708 \u516d\u6708 \u4e03\u6708 \u516b\u6708 \u4e5d\u6708 \u5341\u6708 \u5341\u4e00\u6708 \u5341\u4e8c\u6708".split(" "),A0:"\u4e00\u6708 \u4e8c\u6708 \u4e09\u6708 \u56db\u6708 \u4e94\u6708 \u516d\u6708 \u4e03\u6708 \u516b\u6708 \u4e5d\u6708 \u5341\u6708 \u5341\u4e00\u6708 \u5341\u4e8c\u6708".split(" "),v0:"1\u6708 2\u6708 3\u6708 4\u6708 5\u6708 6\u6708 7\u6708 8\u6708 9\u6708 10\u6708 11\u6708 12\u6708".split(" "),
D0:"1\u6708 2\u6708 3\u6708 4\u6708 5\u6708 6\u6708 7\u6708 8\u6708 9\u6708 10\u6708 11\u6708 12\u6708".split(" "),T0:"\u661f\u671f\u65e5 \u661f\u671f\u4e00 \u661f\u671f\u4e8c \u661f\u671f\u4e09 \u661f\u671f\u56db \u661f\u671f\u4e94 \u661f\u671f\u516d".split(" "),F0:"\u661f\u671f\u65e5 \u661f\u671f\u4e00 \u661f\u671f\u4e8c \u661f\u671f\u4e09 \u661f\u671f\u56db \u661f\u671f\u4e94 \u661f\u671f\u516d".split(" "),x0:"\u5468\u65e5 \u5468\u4e00 \u5468\u4e8c \u5468\u4e09 \u5468\u56db \u5468\u4e94 \u5468\u516d".split(" "),
E0:"\u5468\u65e5 \u5468\u4e00 \u5468\u4e8c \u5468\u4e09 \u5468\u56db \u5468\u4e94 \u5468\u516d".split(" "),j0:"\u65e5\u4e00\u4e8c\u4e09\u56db\u4e94\u516d".split(""),C0:"\u65e5\u4e00\u4e8c\u4e09\u56db\u4e94\u516d".split(""),w0:["1\u5b63\u5ea6","2\u5b63\u5ea6","3\u5b63\u5ea6","4\u5b63\u5ea6"],r0:["\u7b2c\u4e00\u5b63\u5ea6","\u7b2c\u4e8c\u5b63\u5ea6","\u7b2c\u4e09\u5b63\u5ea6","\u7b2c\u56db\u5b63\u5ea6"],nY:["\u4e0a\u5348","\u4e0b\u5348"],BY:["y\u5e74M\u6708d\u65e5EEEE","y\u5e74M\u6708d\u65e5","y\u5e74M\u6708d\u65e5",
"y/M/d"],J0:["zzzz HH:mm:ss","z HH:mm:ss","HH:mm:ss","HH:mm"],CY:["{1} {0}","{1} {0}","{1} {0}","{1} {0}"],HP:0,U0:[5,6],IP:6};g.k=jfb.prototype;g.k.IS=Mfb.HP;g.k.JS=Mfb.IP;g.k.clone=function(){var a=new jfb(this.date);a.IS=this.IS;a.JS=this.JS;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.u||a.j){var b=this.getMonth()+a.j+12*a.u,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),R5(this,a.getDate()))};
g.k.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+ffb(Math.abs(a),b?6:4),ffb(this.getMonth()+1,2),ffb(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var Nfb=new g.Kp("addUpcomingEventReminderEndpoint");var Ofb=new g.Kp("removeUpcomingEventReminderEndpoint");var Pfb=new g.Kp("updateUpcomingEventReminderButtonStateCommand");var mfb=new g.Kp("upcomingEventReminderButtonRenderer"),sfb=new g.Kp("upcomingEventReminderButtonStateRenderer");g.v(S5,g.hR);S5.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.hR.prototype.hide.call(this)};
S5.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.hR.prototype.show.call(this)};
S5.prototype.ra=function(){g.Za(this.j);g.hR.prototype.ra.call(this)};g.v(T5,g.S);
T5.prototype.D=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.B(a.toggledServiceEndpoint):this.B(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;U5(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.tb)this.j.Bb();else{var b=pfb(this);b&&this.B(b.serviceEndpoint||b.command);b=(null==(a=g.L(null==b?void 0:b.command,g.EO))?void 0:a.commands)||[];a:{a=g.t(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.L(c.value,
g.b9a))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new S5(this.F,this.buttonElement),this.j.Da(this.element),g.D(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.B,this));b=this.j;b.menuPopupRenderer=a;lfb(b)}};
T5.prototype.B=function(a){var b=g.L(a,Nfb),c=g.L(a,Ofb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(rfb(this,e,d.params),a=g.t(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.L(b,Pfb)){this.u=g.L(b,Pfb).state;U5(this);break}}};g.v(tfb,g.S);g.k=tfb.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.La=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.u=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.MX():ufb(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new T5(this.api),this.j.Da(this.Ca("ytp-offline-slate-buttons")),g.D(this,this.j)),nfb(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&nfb(this.j,null,null);this.u=a}else this.u=null;this.RX()};
g.k.RX=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Fb(),d=this.getVideoData();b=d.isLivePlayback&&(g.AM(c)||g.R(c,2)||g.R(c,64));var e=2===d.autonavState&&g.R(c,2);c=c.bd()&&!g.wK(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u?this.tb?(null==a?0:g.ML(a,2))&&!this.getVideoData().dl&&(g.io(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.io(this.B,"ytp-offline-slate-bar-fade"),this.D.start()):(this.show(),this.C.start(),this.api.ea("offlineslatestatechange"),
this.I&&this.api.vz()):this.tb&&(this.hide(),this.api.ea("offlineslatestatechange"))};
g.k.MX=function(){var a,b,c,d,e=null==(a=this.u)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.Qa()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(ufb(this,e),this.countdownTimer.stop()):(ufb(this,e,g.LO(b-a)),g.Zn(this.countdownTimer)))};
g.k.ra=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.S.prototype.ra.call(this)};V5.prototype.u=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
V5.prototype.isExpired=function(){return 6E4<(0,g.M)()-this.B};
V5.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.v(Cfb,g.RR);g.k=Cfb.prototype;g.k.ra=function(){Z5(this);this.player.Kf("heartbeat");g.RR.prototype.ra.call(this)};
g.k.onCueRangeEnter=function(){this.J=!0;X5(this,2E3)};
g.k.AC=function(a){this.heartbeatParams=a;X5(this,2E3)};
g.k.nZ=function(a){var b;8!==this.player.getPresentingPlayerType()&&"UNPLAYABLE"!==(null==(b=this.j)?void 0:b.status)&&(g.R(a.state,2)||g.R(a.state,64)?(Z5(this),this.C&&(this.J=!0,X5(this,1E3))):(g.R(a.state,1)||g.R(a.state,8))&&X5(this,2E3))};
g.k.oZ=function(){3!==this.player.getPresentingPlayerType()&&X5(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Lk=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.XF=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.Tx("heartbeatActionPlayerTransitioned",a)};
g.k.zf=function(a){var b="LICENSE",c=Ffb(a);if(c)return c.reason||g.zS[b]||"";(a=a.match(Gfb))&&(a=Number(a[1]))&&(b=g.wDa(a));return g.zS[b]||""};
g.k.aC=function(){return!!this.offlineSlate&&this.offlineSlate.tb};
var Gfb=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.QR("heartbeat",Cfb);})(_yt_player);
